# Generated by Django 3.2.4 on 2021-06-23 19:34

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETE_CART', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=64)),
                ('imagen', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/img'), upload_to='')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_producto', to='JAGUARETE_CART.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('lista_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JAGUARETE_CART.producto')),
            ],
        ),
    ]
