# Generated by Django 3.2.4 on 2021-07-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARRITO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto'},
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
